import type {
  VariantAttributeDefinition,
  VariantGenerationDefaults,
  VariantRow,
} from "./types";

/** Cartesian product of value lists (each inner array is one axis). */
export function cartesianValues<T>(axes: T[][]): T[][] {
  if (!axes.length) return [];
  return axes.reduce<T[][]>(
    (acc, axis) => acc.flatMap((prefix) => axis.map((v) => [...prefix, v])),
    [[]]
  );
}

function genVariantId() {
  return crypto.randomUUID();
}

/**
 * Builds one row per combination of attribute values (full matrix).
 * Skips when any attribute has zero values.
 *
 * NOTE: SKUs are generated by the backend, so the frontend matrix only
 * carries the attribute combination and default inventory fields.
 */
export function buildVariantMatrix(
  definitions: VariantAttributeDefinition[],
  defaults: VariantGenerationDefaults
): VariantRow[] {
  if (!definitions.length) return [];
  if (definitions.some((d) => !d.values.length)) return [];

  const tuples = cartesianValues(definitions.map((d) => d.values));

  return tuples.map((vals) => {
    const combo: Record<string, string> = {};
    const selectionIds: string[] = [];
    definitions.forEach((d, i) => {
      const val = vals[i] ?? "";
      combo[d.id] = val;
      const valueId = d.valueIdMap?.[val];
      if (valueId) selectionIds.push(valueId);
    });
    return {
      id: genVariantId(),
      combo,
      selectionIds,
      isLocalOnly: true,
      moq: defaults.moq,
      stock: defaults.stock,
      price: defaults.price,
      weightGrams: defaults.weightGrams,
      lengthCm: defaults.lengthCm,
      widthCm: defaults.widthCm,
      heightCm: defaults.heightCm,
      barcode: defaults.barcode.trim(),
      imageUrl: "",
    };
  });
}
